/**
 * db.tsx — thin wrapper around the kv_store table that satisfies the
 * `user_id NOT NULL` constraint present on the real Supabase table.
 *
 * kv_store.tsx is autogenerated/protected and only inserts {key, value}.
 * This file bypasses it for writes so we can always supply user_id.
 */

import { createClient } from "npm:@supabase/supabase-js";

const TABLE = "kv_store_991222a2";

// A well-known nil UUID used for system/non-user records (products, seeds).
export const SYSTEM_USER_ID = "00000000-0000-0000-0000-000000000000";

function client() {
  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
}

/**
 * Upsert a key-value pair, always providing a user_id so the NOT NULL
 * constraint is satisfied.  Pass the owner's UUID for user-owned records
 * (profiles, orders); omit / pass undefined for system records (products).
 */
export const set = async (
  key: string,
  value: any,
  userId: string = SYSTEM_USER_ID,
): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from(TABLE).upsert({ key, value, user_id: userId });
  if (error) throw new Error(error.message);
};

/**
 * Read a single key using the service-role client, which bypasses all RLS
 * policies. This guarantees profile/order reads always succeed regardless of
 * the RLS SELECT policy on the kv_store table.
 */
export const get = async (key: string): Promise<any | null> => {
  const supabase = client();
  const { data, error } = await supabase
    .from(TABLE)
    .select("value")
    .eq("key", key)
    .maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value ?? null;
};

/**
 * Read all rows whose key starts with the given prefix, using the
 * service-role client (bypasses RLS).
 */
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from(TABLE)
    .select("value")
    .like("key", `${prefix}%`);
  if (error) throw new Error(error.message);
  return (data ?? []).map((row: any) => row.value);
};

/**
 * Delete a key using the service-role client.
 */
export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from(TABLE).delete().eq("key", key);
  if (error) throw new Error(error.message);
};